// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RannaTask.DAL.Contexts;

#nullable disable

namespace RannaTask.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250201220800_NewUserAndCustomerRelations")]
    partial class NewUserAndCustomerRelations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RannaTask.Entities.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2025, 2, 2, 1, 7, 59, 663, DateTimeKind.Local).AddTicks(7333),
                            Email = "ahmetsasmaz@gmail.com",
                            FirstName = "Ahmet",
                            LastName = "Şaşmaz",
                            PasswordHash = "$2a$10$9yPu3TyqMitKGpYxbp/o1e3XNFUwztQ7g0K.sYY2K6t3sUuDmXZPy",
                            Username = "ahmetsasmaz"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2025, 2, 2, 1, 7, 59, 663, DateTimeKind.Local).AddTicks(7344),
                            Email = "mehmetuzulmez@gmail.com",
                            FirstName = "Mehmet",
                            LastName = "Üzülmez",
                            PasswordHash = "$2a$10$9yPu3TyqMitKGpYxbp/o1e3XNFUwztQ7g0K.sYY2K6t3sUuDmXZPy",
                            Username = "mehmetuzulmez"
                        });
                });

            modelBuilder.Entity("RannaTask.Entities.Entities.Manager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Manager");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2025, 2, 2, 1, 7, 59, 662, DateTimeKind.Local).AddTicks(8257),
                            Email = "manager@gmail.com",
                            FirstName = "Manager",
                            LastName = ""
                        });
                });

            modelBuilder.Entity("RannaTask.Entities.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "ABC123",
                            Created = new DateTime(2025, 2, 2, 1, 7, 59, 663, DateTimeKind.Local).AddTicks(7980),
                            Name = "AbcYazılım",
                            Price = 100000m
                        });
                });

            modelBuilder.Entity("RannaTask.Entities.Entities.SupportForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("SupportForms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2025, 2, 2, 1, 7, 59, 663, DateTimeKind.Local).AddTicks(9287),
                            CustomerId = 1,
                            Message = "TEst Deneme",
                            Status = 0,
                            Subject = "Test"
                        });
                });

            modelBuilder.Entity("RannaTask.Entities.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2025, 2, 2, 1, 7, 59, 664, DateTimeKind.Local).AddTicks(49),
                            PasswordHash = "$2a$10$9yPu3TyqMitKGpYxbp/o1e3XNFUwztQ7g0K.sYY2K6t3sUuDmXZPy",
                            Role = "PanelUser",
                            Username = "Manager1"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2025, 2, 2, 1, 7, 59, 664, DateTimeKind.Local).AddTicks(54),
                            PasswordHash = "asdasd",
                            Role = "PanelUser",
                            Username = "Manager2"
                        });
                });

            modelBuilder.Entity("RannaTask.Entities.Entities.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("UserRole");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2025, 2, 2, 1, 7, 59, 663, DateTimeKind.Local).AddTicks(6714),
                            Name = "Manager",
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2025, 2, 2, 1, 7, 59, 663, DateTimeKind.Local).AddTicks(6720),
                            Name = "Customer",
                            Type = (byte)2
                        });
                });

            modelBuilder.Entity("RannaTask.Entities.Entities.SupportForm", b =>
                {
                    b.HasOne("RannaTask.Entities.Entities.Customer", null)
                        .WithMany("SupportForms")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RannaTask.Entities.Entities.Customer", b =>
                {
                    b.Navigation("SupportForms");
                });
#pragma warning restore 612, 618
        }
    }
}
