// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RannaTask.DAL.Contexts;

#nullable disable

namespace RannaTask.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RannaTask.Entities.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2025, 2, 1, 15, 13, 29, 494, DateTimeKind.Local).AddTicks(2462),
                            Email = "ahmetsasmaz@gmail.com",
                            FirstName = "Ahmet",
                            LastName = "Şaşmaz"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2025, 2, 1, 15, 13, 29, 494, DateTimeKind.Local).AddTicks(2469),
                            Email = "mehmetuzulmez@gmail.com",
                            FirstName = "Mehmet",
                            LastName = "Üzülmez"
                        });
                });

            modelBuilder.Entity("RannaTask.Entities.Entities.Manager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Managers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2025, 2, 1, 15, 13, 29, 493, DateTimeKind.Local).AddTicks(9926),
                            Email = "manager@gmail.com",
                            FirstName = "Manager",
                            LastName = ""
                        });
                });

            modelBuilder.Entity("RannaTask.Entities.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "ABC123",
                            Created = new DateTime(2025, 2, 1, 15, 13, 29, 494, DateTimeKind.Local).AddTicks(3676),
                            Name = "AbcYazılım",
                            Price = 100000m
                        });
                });

            modelBuilder.Entity("RannaTask.Entities.Entities.SupportForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("SupportForms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2025, 2, 1, 15, 13, 29, 494, DateTimeKind.Local).AddTicks(4866),
                            CustomerId = 1,
                            Message = "TEst Deneme",
                            Status = 0,
                            Subject = "Test"
                        });
                });

            modelBuilder.Entity("RannaTask.Entities.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2025, 2, 1, 15, 13, 29, 494, DateTimeKind.Local).AddTicks(6135),
                            CustomerId = 1,
                            ManagerId = 0,
                            Password = "asdasd",
                            PasswordHash = "asdasd",
                            RoleId = 2,
                            Username = "ahmetsasmaz"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2025, 2, 1, 15, 13, 29, 494, DateTimeKind.Local).AddTicks(6143),
                            CustomerId = 0,
                            ManagerId = 1,
                            Password = "asdasd",
                            PasswordHash = "asdasd",
                            RoleId = 1,
                            Username = "Manager"
                        });
                });

            modelBuilder.Entity("RannaTask.Entities.Entities.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2025, 2, 1, 15, 13, 29, 494, DateTimeKind.Local).AddTicks(1613),
                            Name = "Manager",
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2025, 2, 1, 15, 13, 29, 494, DateTimeKind.Local).AddTicks(1621),
                            Name = "Customer",
                            Type = (byte)2
                        });
                });

            modelBuilder.Entity("RannaTask.Entities.Entities.SupportForm", b =>
                {
                    b.HasOne("RannaTask.Entities.Entities.Customer", null)
                        .WithMany("SupportForms")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RannaTask.Entities.Entities.User", b =>
                {
                    b.HasOne("RannaTask.Entities.Entities.UserRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("RannaTask.Entities.Entities.Customer", b =>
                {
                    b.Navigation("SupportForms");
                });
#pragma warning restore 612, 618
        }
    }
}
